/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MunasabtiBookingSlugRouteImport } from './routes/munasabti-booking.$slug'
import { Route as BookingSplatRouteImport } from './routes/booking.$'
import { Route as MainSuppliesRouteImport } from './routes/_main.supplies'
import { Route as MainSettingsRouteImport } from './routes/_main.settings'
import { Route as MainProfitsRouteImport } from './routes/_main.profits'
import { Route as MainNotificationsRouteImport } from './routes/_main.notifications'
import { Route as MainDecorationsRouteImport } from './routes/_main.decorations'
import { Route as MainCustomersRouteImport } from './routes/_main.customers'
import { Route as MainCalendarRouteImport } from './routes/_main.calendar'
import { Route as MainBookingsRouteImport } from './routes/_main.bookings'
import { Route as MainBookingRequestsRouteImport } from './routes/_main.booking-requests'
import { Route as MainAnalyticsRouteImport } from './routes/_main.analytics'
import { Route as MunasabtiBookingSlugIndexRouteImport } from './routes/munasabti-booking.$slug.index'
import { Route as MunasabtiBookingSlugSuppliesRouteImport } from './routes/munasabti-booking.$slug.supplies'
import { Route as MunasabtiBookingSlugRequestRouteImport } from './routes/munasabti-booking.$slug.request'
import { Route as MunasabtiBookingSlugDecorationsRouteImport } from './routes/munasabti-booking.$slug.decorations'
import { Route as MunasabtiBookingSlugDecorationsIdRouteImport } from './routes/munasabti-booking.$slug.decorations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MunasabtiBookingSlugRoute = MunasabtiBookingSlugRouteImport.update({
  id: '/munasabti-booking/$slug',
  path: '/munasabti-booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSplatRoute = BookingSplatRouteImport.update({
  id: '/booking/$',
  path: '/booking/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSuppliesRoute = MainSuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProfitsRoute = MainProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => MainRoute,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRoute,
} as any)
const MainDecorationsRoute = MainDecorationsRouteImport.update({
  id: '/decorations',
  path: '/decorations',
  getParentRoute: () => MainRoute,
} as any)
const MainCustomersRoute = MainCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MainRoute,
} as any)
const MainCalendarRoute = MainCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingsRoute = MainBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingRequestsRoute = MainBookingRequestsRouteImport.update({
  id: '/booking-requests',
  path: '/booking-requests',
  getParentRoute: () => MainRoute,
} as any)
const MainAnalyticsRoute = MainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRoute,
} as any)
const MunasabtiBookingSlugIndexRoute =
  MunasabtiBookingSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugSuppliesRoute =
  MunasabtiBookingSlugSuppliesRouteImport.update({
    id: '/supplies',
    path: '/supplies',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugRequestRoute =
  MunasabtiBookingSlugRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugDecorationsRoute =
  MunasabtiBookingSlugDecorationsRouteImport.update({
    id: '/decorations',
    path: '/decorations',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugDecorationsIdRoute =
  MunasabtiBookingSlugDecorationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MunasabtiBookingSlugDecorationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/booking-requests': typeof MainBookingRequestsRoute
  '/bookings': typeof MainBookingsRoute
  '/calendar': typeof MainCalendarRoute
  '/customers': typeof MainCustomersRoute
  '/decorations': typeof MainDecorationsRoute
  '/notifications': typeof MainNotificationsRoute
  '/profits': typeof MainProfitsRoute
  '/settings': typeof MainSettingsRoute
  '/supplies': typeof MainSuppliesRoute
  '/booking/$': typeof BookingSplatRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugRouteWithChildren
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/munasabti-booking/$slug/': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/booking-requests': typeof MainBookingRequestsRoute
  '/bookings': typeof MainBookingsRoute
  '/calendar': typeof MainCalendarRoute
  '/customers': typeof MainCustomersRoute
  '/decorations': typeof MainDecorationsRoute
  '/notifications': typeof MainNotificationsRoute
  '/profits': typeof MainProfitsRoute
  '/settings': typeof MainSettingsRoute
  '/supplies': typeof MainSuppliesRoute
  '/booking/$': typeof BookingSplatRoute
  '/': typeof MainIndexRoute
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_main/analytics': typeof MainAnalyticsRoute
  '/_main/booking-requests': typeof MainBookingRequestsRoute
  '/_main/bookings': typeof MainBookingsRoute
  '/_main/calendar': typeof MainCalendarRoute
  '/_main/customers': typeof MainCustomersRoute
  '/_main/decorations': typeof MainDecorationsRoute
  '/_main/notifications': typeof MainNotificationsRoute
  '/_main/profits': typeof MainProfitsRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/supplies': typeof MainSuppliesRoute
  '/booking/$': typeof BookingSplatRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/munasabti-booking/$slug/': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/booking-requests'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/decorations'
    | '/notifications'
    | '/profits'
    | '/settings'
    | '/supplies'
    | '/booking/$'
    | '/munasabti-booking/$slug'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/munasabti-booking/$slug/'
    | '/munasabti-booking/$slug/decorations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/booking-requests'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/decorations'
    | '/notifications'
    | '/profits'
    | '/settings'
    | '/supplies'
    | '/booking/$'
    | '/'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/munasabti-booking/$slug'
    | '/munasabti-booking/$slug/decorations/$id'
  id:
    | '__root__'
    | '/_main'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_main/analytics'
    | '/_main/booking-requests'
    | '/_main/bookings'
    | '/_main/calendar'
    | '/_main/customers'
    | '/_main/decorations'
    | '/_main/notifications'
    | '/_main/profits'
    | '/_main/settings'
    | '/_main/supplies'
    | '/booking/$'
    | '/munasabti-booking/$slug'
    | '/_main/'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/munasabti-booking/$slug/'
    | '/munasabti-booking/$slug/decorations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BookingSplatRoute: typeof BookingSplatRoute
  MunasabtiBookingSlugRoute: typeof MunasabtiBookingSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/munasabti-booking/$slug': {
      id: '/munasabti-booking/$slug'
      path: '/munasabti-booking/$slug'
      fullPath: '/munasabti-booking/$slug'
      preLoaderRoute: typeof MunasabtiBookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$': {
      id: '/booking/$'
      path: '/booking/$'
      fullPath: '/booking/$'
      preLoaderRoute: typeof BookingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/supplies': {
      id: '/_main/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof MainSuppliesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profits': {
      id: '/_main/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof MainProfitsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/notifications': {
      id: '/_main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/decorations': {
      id: '/_main/decorations'
      path: '/decorations'
      fullPath: '/decorations'
      preLoaderRoute: typeof MainDecorationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/customers': {
      id: '/_main/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MainCustomersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/calendar': {
      id: '/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof MainCalendarRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bookings': {
      id: '/_main/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof MainBookingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/booking-requests': {
      id: '/_main/booking-requests'
      path: '/booking-requests'
      fullPath: '/booking-requests'
      preLoaderRoute: typeof MainBookingRequestsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsRouteImport
      parentRoute: typeof MainRoute
    }
    '/munasabti-booking/$slug/': {
      id: '/munasabti-booking/$slug/'
      path: '/'
      fullPath: '/munasabti-booking/$slug/'
      preLoaderRoute: typeof MunasabtiBookingSlugIndexRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/supplies': {
      id: '/munasabti-booking/$slug/supplies'
      path: '/supplies'
      fullPath: '/munasabti-booking/$slug/supplies'
      preLoaderRoute: typeof MunasabtiBookingSlugSuppliesRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/request': {
      id: '/munasabti-booking/$slug/request'
      path: '/request'
      fullPath: '/munasabti-booking/$slug/request'
      preLoaderRoute: typeof MunasabtiBookingSlugRequestRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/decorations': {
      id: '/munasabti-booking/$slug/decorations'
      path: '/decorations'
      fullPath: '/munasabti-booking/$slug/decorations'
      preLoaderRoute: typeof MunasabtiBookingSlugDecorationsRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/decorations/$id': {
      id: '/munasabti-booking/$slug/decorations/$id'
      path: '/$id'
      fullPath: '/munasabti-booking/$slug/decorations/$id'
      preLoaderRoute: typeof MunasabtiBookingSlugDecorationsIdRouteImport
      parentRoute: typeof MunasabtiBookingSlugDecorationsRoute
    }
  }
}

interface MainRouteChildren {
  MainAnalyticsRoute: typeof MainAnalyticsRoute
  MainBookingRequestsRoute: typeof MainBookingRequestsRoute
  MainBookingsRoute: typeof MainBookingsRoute
  MainCalendarRoute: typeof MainCalendarRoute
  MainCustomersRoute: typeof MainCustomersRoute
  MainDecorationsRoute: typeof MainDecorationsRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainProfitsRoute: typeof MainProfitsRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainSuppliesRoute: typeof MainSuppliesRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAnalyticsRoute: MainAnalyticsRoute,
  MainBookingRequestsRoute: MainBookingRequestsRoute,
  MainBookingsRoute: MainBookingsRoute,
  MainCalendarRoute: MainCalendarRoute,
  MainCustomersRoute: MainCustomersRoute,
  MainDecorationsRoute: MainDecorationsRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainProfitsRoute: MainProfitsRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainSuppliesRoute: MainSuppliesRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface MunasabtiBookingSlugDecorationsRouteChildren {
  MunasabtiBookingSlugDecorationsIdRoute: typeof MunasabtiBookingSlugDecorationsIdRoute
}

const MunasabtiBookingSlugDecorationsRouteChildren: MunasabtiBookingSlugDecorationsRouteChildren =
  {
    MunasabtiBookingSlugDecorationsIdRoute:
      MunasabtiBookingSlugDecorationsIdRoute,
  }

const MunasabtiBookingSlugDecorationsRouteWithChildren =
  MunasabtiBookingSlugDecorationsRoute._addFileChildren(
    MunasabtiBookingSlugDecorationsRouteChildren,
  )

interface MunasabtiBookingSlugRouteChildren {
  MunasabtiBookingSlugDecorationsRoute: typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  MunasabtiBookingSlugRequestRoute: typeof MunasabtiBookingSlugRequestRoute
  MunasabtiBookingSlugSuppliesRoute: typeof MunasabtiBookingSlugSuppliesRoute
  MunasabtiBookingSlugIndexRoute: typeof MunasabtiBookingSlugIndexRoute
}

const MunasabtiBookingSlugRouteChildren: MunasabtiBookingSlugRouteChildren = {
  MunasabtiBookingSlugDecorationsRoute:
    MunasabtiBookingSlugDecorationsRouteWithChildren,
  MunasabtiBookingSlugRequestRoute: MunasabtiBookingSlugRequestRoute,
  MunasabtiBookingSlugSuppliesRoute: MunasabtiBookingSlugSuppliesRoute,
  MunasabtiBookingSlugIndexRoute: MunasabtiBookingSlugIndexRoute,
}

const MunasabtiBookingSlugRouteWithChildren =
  MunasabtiBookingSlugRoute._addFileChildren(MunasabtiBookingSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BookingSplatRoute: BookingSplatRoute,
  MunasabtiBookingSlugRoute: MunasabtiBookingSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
