/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MunasabtiBookingSlugRouteImport } from './routes/munasabti-booking.$slug'
import { Route as BookingSplatRouteImport } from './routes/booking.$'
import { Route as MunasabtiBookingSlugIndexRouteImport } from './routes/munasabti-booking.$slug.index'
import { Route as MainMunasabtiManagerIndexRouteImport } from './routes/_main.munasabti-manager.index'
import { Route as MunasabtiBookingSlugSuppliesRouteImport } from './routes/munasabti-booking.$slug.supplies'
import { Route as MunasabtiBookingSlugRequestRouteImport } from './routes/munasabti-booking.$slug.request'
import { Route as MunasabtiBookingSlugDecorationsRouteImport } from './routes/munasabti-booking.$slug.decorations'
import { Route as MainMunasabtiManagerSuppliesRouteImport } from './routes/_main.munasabti-manager.supplies'
import { Route as MainMunasabtiManagerSettingsRouteImport } from './routes/_main.munasabti-manager.settings'
import { Route as MainMunasabtiManagerProfitsRouteImport } from './routes/_main.munasabti-manager.profits'
import { Route as MainMunasabtiManagerNotificationsRouteImport } from './routes/_main.munasabti-manager.notifications'
import { Route as MainMunasabtiManagerDecorationsRouteImport } from './routes/_main.munasabti-manager.decorations'
import { Route as MainMunasabtiManagerCustomersRouteImport } from './routes/_main.munasabti-manager.customers'
import { Route as MainMunasabtiManagerCalendarRouteImport } from './routes/_main.munasabti-manager.calendar'
import { Route as MainMunasabtiManagerBookingsRouteImport } from './routes/_main.munasabti-manager.bookings'
import { Route as MainMunasabtiManagerBookingRequestsRouteImport } from './routes/_main.munasabti-manager.booking-requests'
import { Route as MainMunasabtiManagerAnalyticsRouteImport } from './routes/_main.munasabti-manager.analytics'
import { Route as MunasabtiBookingSlugDecorationsIdRouteImport } from './routes/munasabti-booking.$slug.decorations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MunasabtiBookingSlugRoute = MunasabtiBookingSlugRouteImport.update({
  id: '/munasabti-booking/$slug',
  path: '/munasabti-booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSplatRoute = BookingSplatRouteImport.update({
  id: '/booking/$',
  path: '/booking/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MunasabtiBookingSlugIndexRoute =
  MunasabtiBookingSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MainMunasabtiManagerIndexRoute =
  MainMunasabtiManagerIndexRouteImport.update({
    id: '/munasabti-manager/',
    path: '/munasabti-manager/',
    getParentRoute: () => MainRoute,
  } as any)
const MunasabtiBookingSlugSuppliesRoute =
  MunasabtiBookingSlugSuppliesRouteImport.update({
    id: '/supplies',
    path: '/supplies',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugRequestRoute =
  MunasabtiBookingSlugRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MunasabtiBookingSlugDecorationsRoute =
  MunasabtiBookingSlugDecorationsRouteImport.update({
    id: '/decorations',
    path: '/decorations',
    getParentRoute: () => MunasabtiBookingSlugRoute,
  } as any)
const MainMunasabtiManagerSuppliesRoute =
  MainMunasabtiManagerSuppliesRouteImport.update({
    id: '/munasabti-manager/supplies',
    path: '/munasabti-manager/supplies',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerSettingsRoute =
  MainMunasabtiManagerSettingsRouteImport.update({
    id: '/munasabti-manager/settings',
    path: '/munasabti-manager/settings',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerProfitsRoute =
  MainMunasabtiManagerProfitsRouteImport.update({
    id: '/munasabti-manager/profits',
    path: '/munasabti-manager/profits',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerNotificationsRoute =
  MainMunasabtiManagerNotificationsRouteImport.update({
    id: '/munasabti-manager/notifications',
    path: '/munasabti-manager/notifications',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerDecorationsRoute =
  MainMunasabtiManagerDecorationsRouteImport.update({
    id: '/munasabti-manager/decorations',
    path: '/munasabti-manager/decorations',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerCustomersRoute =
  MainMunasabtiManagerCustomersRouteImport.update({
    id: '/munasabti-manager/customers',
    path: '/munasabti-manager/customers',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerCalendarRoute =
  MainMunasabtiManagerCalendarRouteImport.update({
    id: '/munasabti-manager/calendar',
    path: '/munasabti-manager/calendar',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerBookingsRoute =
  MainMunasabtiManagerBookingsRouteImport.update({
    id: '/munasabti-manager/bookings',
    path: '/munasabti-manager/bookings',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerBookingRequestsRoute =
  MainMunasabtiManagerBookingRequestsRouteImport.update({
    id: '/munasabti-manager/booking-requests',
    path: '/munasabti-manager/booking-requests',
    getParentRoute: () => MainRoute,
  } as any)
const MainMunasabtiManagerAnalyticsRoute =
  MainMunasabtiManagerAnalyticsRouteImport.update({
    id: '/munasabti-manager/analytics',
    path: '/munasabti-manager/analytics',
    getParentRoute: () => MainRoute,
  } as any)
const MunasabtiBookingSlugDecorationsIdRoute =
  MunasabtiBookingSlugDecorationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MunasabtiBookingSlugDecorationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/booking/$': typeof BookingSplatRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugRouteWithChildren
  '/munasabti-manager/analytics': typeof MainMunasabtiManagerAnalyticsRoute
  '/munasabti-manager/booking-requests': typeof MainMunasabtiManagerBookingRequestsRoute
  '/munasabti-manager/bookings': typeof MainMunasabtiManagerBookingsRoute
  '/munasabti-manager/calendar': typeof MainMunasabtiManagerCalendarRoute
  '/munasabti-manager/customers': typeof MainMunasabtiManagerCustomersRoute
  '/munasabti-manager/decorations': typeof MainMunasabtiManagerDecorationsRoute
  '/munasabti-manager/notifications': typeof MainMunasabtiManagerNotificationsRoute
  '/munasabti-manager/profits': typeof MainMunasabtiManagerProfitsRoute
  '/munasabti-manager/settings': typeof MainMunasabtiManagerSettingsRoute
  '/munasabti-manager/supplies': typeof MainMunasabtiManagerSuppliesRoute
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/munasabti-manager/': typeof MainMunasabtiManagerIndexRoute
  '/munasabti-booking/$slug/': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MainRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/booking/$': typeof BookingSplatRoute
  '/munasabti-manager/analytics': typeof MainMunasabtiManagerAnalyticsRoute
  '/munasabti-manager/booking-requests': typeof MainMunasabtiManagerBookingRequestsRoute
  '/munasabti-manager/bookings': typeof MainMunasabtiManagerBookingsRoute
  '/munasabti-manager/calendar': typeof MainMunasabtiManagerCalendarRoute
  '/munasabti-manager/customers': typeof MainMunasabtiManagerCustomersRoute
  '/munasabti-manager/decorations': typeof MainMunasabtiManagerDecorationsRoute
  '/munasabti-manager/notifications': typeof MainMunasabtiManagerNotificationsRoute
  '/munasabti-manager/profits': typeof MainMunasabtiManagerProfitsRoute
  '/munasabti-manager/settings': typeof MainMunasabtiManagerSettingsRoute
  '/munasabti-manager/supplies': typeof MainMunasabtiManagerSuppliesRoute
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/munasabti-manager': typeof MainMunasabtiManagerIndexRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/booking/$': typeof BookingSplatRoute
  '/munasabti-booking/$slug': typeof MunasabtiBookingSlugRouteWithChildren
  '/_main/munasabti-manager/analytics': typeof MainMunasabtiManagerAnalyticsRoute
  '/_main/munasabti-manager/booking-requests': typeof MainMunasabtiManagerBookingRequestsRoute
  '/_main/munasabti-manager/bookings': typeof MainMunasabtiManagerBookingsRoute
  '/_main/munasabti-manager/calendar': typeof MainMunasabtiManagerCalendarRoute
  '/_main/munasabti-manager/customers': typeof MainMunasabtiManagerCustomersRoute
  '/_main/munasabti-manager/decorations': typeof MainMunasabtiManagerDecorationsRoute
  '/_main/munasabti-manager/notifications': typeof MainMunasabtiManagerNotificationsRoute
  '/_main/munasabti-manager/profits': typeof MainMunasabtiManagerProfitsRoute
  '/_main/munasabti-manager/settings': typeof MainMunasabtiManagerSettingsRoute
  '/_main/munasabti-manager/supplies': typeof MainMunasabtiManagerSuppliesRoute
  '/munasabti-booking/$slug/decorations': typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  '/munasabti-booking/$slug/request': typeof MunasabtiBookingSlugRequestRoute
  '/munasabti-booking/$slug/supplies': typeof MunasabtiBookingSlugSuppliesRoute
  '/_main/munasabti-manager/': typeof MainMunasabtiManagerIndexRoute
  '/munasabti-booking/$slug/': typeof MunasabtiBookingSlugIndexRoute
  '/munasabti-booking/$slug/decorations/$id': typeof MunasabtiBookingSlugDecorationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/booking/$'
    | '/munasabti-booking/$slug'
    | '/munasabti-manager/analytics'
    | '/munasabti-manager/booking-requests'
    | '/munasabti-manager/bookings'
    | '/munasabti-manager/calendar'
    | '/munasabti-manager/customers'
    | '/munasabti-manager/decorations'
    | '/munasabti-manager/notifications'
    | '/munasabti-manager/profits'
    | '/munasabti-manager/settings'
    | '/munasabti-manager/supplies'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/munasabti-manager/'
    | '/munasabti-booking/$slug/'
    | '/munasabti-booking/$slug/decorations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/booking/$'
    | '/munasabti-manager/analytics'
    | '/munasabti-manager/booking-requests'
    | '/munasabti-manager/bookings'
    | '/munasabti-manager/calendar'
    | '/munasabti-manager/customers'
    | '/munasabti-manager/decorations'
    | '/munasabti-manager/notifications'
    | '/munasabti-manager/profits'
    | '/munasabti-manager/settings'
    | '/munasabti-manager/supplies'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/munasabti-manager'
    | '/munasabti-booking/$slug'
    | '/munasabti-booking/$slug/decorations/$id'
  id:
    | '__root__'
    | '/_main'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/booking/$'
    | '/munasabti-booking/$slug'
    | '/_main/munasabti-manager/analytics'
    | '/_main/munasabti-manager/booking-requests'
    | '/_main/munasabti-manager/bookings'
    | '/_main/munasabti-manager/calendar'
    | '/_main/munasabti-manager/customers'
    | '/_main/munasabti-manager/decorations'
    | '/_main/munasabti-manager/notifications'
    | '/_main/munasabti-manager/profits'
    | '/_main/munasabti-manager/settings'
    | '/_main/munasabti-manager/supplies'
    | '/munasabti-booking/$slug/decorations'
    | '/munasabti-booking/$slug/request'
    | '/munasabti-booking/$slug/supplies'
    | '/_main/munasabti-manager/'
    | '/munasabti-booking/$slug/'
    | '/munasabti-booking/$slug/decorations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BookingSplatRoute: typeof BookingSplatRoute
  MunasabtiBookingSlugRoute: typeof MunasabtiBookingSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munasabti-booking/$slug': {
      id: '/munasabti-booking/$slug'
      path: '/munasabti-booking/$slug'
      fullPath: '/munasabti-booking/$slug'
      preLoaderRoute: typeof MunasabtiBookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$': {
      id: '/booking/$'
      path: '/booking/$'
      fullPath: '/booking/$'
      preLoaderRoute: typeof BookingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munasabti-booking/$slug/': {
      id: '/munasabti-booking/$slug/'
      path: '/'
      fullPath: '/munasabti-booking/$slug/'
      preLoaderRoute: typeof MunasabtiBookingSlugIndexRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/_main/munasabti-manager/': {
      id: '/_main/munasabti-manager/'
      path: '/munasabti-manager'
      fullPath: '/munasabti-manager/'
      preLoaderRoute: typeof MainMunasabtiManagerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/munasabti-booking/$slug/supplies': {
      id: '/munasabti-booking/$slug/supplies'
      path: '/supplies'
      fullPath: '/munasabti-booking/$slug/supplies'
      preLoaderRoute: typeof MunasabtiBookingSlugSuppliesRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/request': {
      id: '/munasabti-booking/$slug/request'
      path: '/request'
      fullPath: '/munasabti-booking/$slug/request'
      preLoaderRoute: typeof MunasabtiBookingSlugRequestRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/munasabti-booking/$slug/decorations': {
      id: '/munasabti-booking/$slug/decorations'
      path: '/decorations'
      fullPath: '/munasabti-booking/$slug/decorations'
      preLoaderRoute: typeof MunasabtiBookingSlugDecorationsRouteImport
      parentRoute: typeof MunasabtiBookingSlugRoute
    }
    '/_main/munasabti-manager/supplies': {
      id: '/_main/munasabti-manager/supplies'
      path: '/munasabti-manager/supplies'
      fullPath: '/munasabti-manager/supplies'
      preLoaderRoute: typeof MainMunasabtiManagerSuppliesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/settings': {
      id: '/_main/munasabti-manager/settings'
      path: '/munasabti-manager/settings'
      fullPath: '/munasabti-manager/settings'
      preLoaderRoute: typeof MainMunasabtiManagerSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/profits': {
      id: '/_main/munasabti-manager/profits'
      path: '/munasabti-manager/profits'
      fullPath: '/munasabti-manager/profits'
      preLoaderRoute: typeof MainMunasabtiManagerProfitsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/notifications': {
      id: '/_main/munasabti-manager/notifications'
      path: '/munasabti-manager/notifications'
      fullPath: '/munasabti-manager/notifications'
      preLoaderRoute: typeof MainMunasabtiManagerNotificationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/decorations': {
      id: '/_main/munasabti-manager/decorations'
      path: '/munasabti-manager/decorations'
      fullPath: '/munasabti-manager/decorations'
      preLoaderRoute: typeof MainMunasabtiManagerDecorationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/customers': {
      id: '/_main/munasabti-manager/customers'
      path: '/munasabti-manager/customers'
      fullPath: '/munasabti-manager/customers'
      preLoaderRoute: typeof MainMunasabtiManagerCustomersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/calendar': {
      id: '/_main/munasabti-manager/calendar'
      path: '/munasabti-manager/calendar'
      fullPath: '/munasabti-manager/calendar'
      preLoaderRoute: typeof MainMunasabtiManagerCalendarRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/bookings': {
      id: '/_main/munasabti-manager/bookings'
      path: '/munasabti-manager/bookings'
      fullPath: '/munasabti-manager/bookings'
      preLoaderRoute: typeof MainMunasabtiManagerBookingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/booking-requests': {
      id: '/_main/munasabti-manager/booking-requests'
      path: '/munasabti-manager/booking-requests'
      fullPath: '/munasabti-manager/booking-requests'
      preLoaderRoute: typeof MainMunasabtiManagerBookingRequestsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/munasabti-manager/analytics': {
      id: '/_main/munasabti-manager/analytics'
      path: '/munasabti-manager/analytics'
      fullPath: '/munasabti-manager/analytics'
      preLoaderRoute: typeof MainMunasabtiManagerAnalyticsRouteImport
      parentRoute: typeof MainRoute
    }
    '/munasabti-booking/$slug/decorations/$id': {
      id: '/munasabti-booking/$slug/decorations/$id'
      path: '/$id'
      fullPath: '/munasabti-booking/$slug/decorations/$id'
      preLoaderRoute: typeof MunasabtiBookingSlugDecorationsIdRouteImport
      parentRoute: typeof MunasabtiBookingSlugDecorationsRoute
    }
  }
}

interface MainRouteChildren {
  MainMunasabtiManagerAnalyticsRoute: typeof MainMunasabtiManagerAnalyticsRoute
  MainMunasabtiManagerBookingRequestsRoute: typeof MainMunasabtiManagerBookingRequestsRoute
  MainMunasabtiManagerBookingsRoute: typeof MainMunasabtiManagerBookingsRoute
  MainMunasabtiManagerCalendarRoute: typeof MainMunasabtiManagerCalendarRoute
  MainMunasabtiManagerCustomersRoute: typeof MainMunasabtiManagerCustomersRoute
  MainMunasabtiManagerDecorationsRoute: typeof MainMunasabtiManagerDecorationsRoute
  MainMunasabtiManagerNotificationsRoute: typeof MainMunasabtiManagerNotificationsRoute
  MainMunasabtiManagerProfitsRoute: typeof MainMunasabtiManagerProfitsRoute
  MainMunasabtiManagerSettingsRoute: typeof MainMunasabtiManagerSettingsRoute
  MainMunasabtiManagerSuppliesRoute: typeof MainMunasabtiManagerSuppliesRoute
  MainMunasabtiManagerIndexRoute: typeof MainMunasabtiManagerIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainMunasabtiManagerAnalyticsRoute: MainMunasabtiManagerAnalyticsRoute,
  MainMunasabtiManagerBookingRequestsRoute:
    MainMunasabtiManagerBookingRequestsRoute,
  MainMunasabtiManagerBookingsRoute: MainMunasabtiManagerBookingsRoute,
  MainMunasabtiManagerCalendarRoute: MainMunasabtiManagerCalendarRoute,
  MainMunasabtiManagerCustomersRoute: MainMunasabtiManagerCustomersRoute,
  MainMunasabtiManagerDecorationsRoute: MainMunasabtiManagerDecorationsRoute,
  MainMunasabtiManagerNotificationsRoute:
    MainMunasabtiManagerNotificationsRoute,
  MainMunasabtiManagerProfitsRoute: MainMunasabtiManagerProfitsRoute,
  MainMunasabtiManagerSettingsRoute: MainMunasabtiManagerSettingsRoute,
  MainMunasabtiManagerSuppliesRoute: MainMunasabtiManagerSuppliesRoute,
  MainMunasabtiManagerIndexRoute: MainMunasabtiManagerIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface MunasabtiBookingSlugDecorationsRouteChildren {
  MunasabtiBookingSlugDecorationsIdRoute: typeof MunasabtiBookingSlugDecorationsIdRoute
}

const MunasabtiBookingSlugDecorationsRouteChildren: MunasabtiBookingSlugDecorationsRouteChildren =
  {
    MunasabtiBookingSlugDecorationsIdRoute:
      MunasabtiBookingSlugDecorationsIdRoute,
  }

const MunasabtiBookingSlugDecorationsRouteWithChildren =
  MunasabtiBookingSlugDecorationsRoute._addFileChildren(
    MunasabtiBookingSlugDecorationsRouteChildren,
  )

interface MunasabtiBookingSlugRouteChildren {
  MunasabtiBookingSlugDecorationsRoute: typeof MunasabtiBookingSlugDecorationsRouteWithChildren
  MunasabtiBookingSlugRequestRoute: typeof MunasabtiBookingSlugRequestRoute
  MunasabtiBookingSlugSuppliesRoute: typeof MunasabtiBookingSlugSuppliesRoute
  MunasabtiBookingSlugIndexRoute: typeof MunasabtiBookingSlugIndexRoute
}

const MunasabtiBookingSlugRouteChildren: MunasabtiBookingSlugRouteChildren = {
  MunasabtiBookingSlugDecorationsRoute:
    MunasabtiBookingSlugDecorationsRouteWithChildren,
  MunasabtiBookingSlugRequestRoute: MunasabtiBookingSlugRequestRoute,
  MunasabtiBookingSlugSuppliesRoute: MunasabtiBookingSlugSuppliesRoute,
  MunasabtiBookingSlugIndexRoute: MunasabtiBookingSlugIndexRoute,
}

const MunasabtiBookingSlugRouteWithChildren =
  MunasabtiBookingSlugRoute._addFileChildren(MunasabtiBookingSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BookingSplatRoute: BookingSplatRoute,
  MunasabtiBookingSlugRoute: MunasabtiBookingSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
